name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - name: Install conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: predict_pv_yield_nwp
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          conda install black flake8 isort mypy pytest
          pip install -e .
      - name: Check formatting with black
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          black --check predict_pv_yield_nwp
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          flake8
      - name: Check imports with isort
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          isort -rc --check .
      - name: Check types with mypy
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          mypy predict_pv_yield_nwp
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          pytest
