name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install conda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: predict_pv_yield_nwp
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          pip install -e .
      - name: Check formatting with black
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          black --check predict_pv_yield_nwp
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate predict_pv_yield_nwp
          pytest
